.DEFAULT_GOAL := a

a:   #target to convert assembly to machine code
	./make_a_to_m.bat
c:   #target to convert c to machine code
	./make_c_to_m.bat

a_linux:
	# ./make_a_to_m.bat
	chmod +x make_a_to_m.sh
	./make_a_to_m.sh
c_linux:
	# ./make_c_to_m.bat
	chmod +x make_a_to_c.sh
	./make_a_to_m.sh
clean:
	del build